version: "3.3"

services:

  db:
    image: bitnami/mongodb:latest
    environment:
      - ALLOW_EMPTY_PASSWORD=yes
      - MONGODB_DATABASE=test
      - MONGODB_SYSTEM_LOG_VERBOSITY=3
    ports: 
      - '27017:27017'