import * as React from 'react';
import type { NextPage } from 'next'
import Head from 'next/head'
import { FormRegister } from '../components/FormRegister';

const Home: NextPage = () => {
  return (
    <React.Fragment>

      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <FormRegister/>

    </React.Fragment>
  )
}

export default Home
